package e2e

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"testing"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

// TestStorageS3MinIO exercises storage.provider: s3 against real MinIO
// (use_path_style): upload a datasheet through the app, read it back through
// the app, verify the object exists in MinIO directly, delete through the
// app, and verify it is gone from MinIO.
func TestStorageS3MinIO(t *testing.T) {
	base := appURL(t)
	c := client(t)

	endpoint := envOr("QA_S3_ENDPOINT", "http://127.0.0.1:59000")
	u, err := url.Parse(endpoint)
	if err != nil {
		t.Fatalf("bad QA_S3_ENDPOINT: %v", err)
	}
	mc, err := minio.New(u.Host, &minio.Options{
		Creds:  credentials.NewStaticV4(envOr("QA_S3_ACCESS_KEY", "minioadmin"), envOr("QA_S3_SECRET_KEY", "minioadmin"), ""),
		Secure: u.Scheme == "https",
	})
	if err != nil {
		t.Fatalf("minio client: %v", err)
	}
	bucket := envOr("QA_S3_BUCKET", "warehouse")
	ctx := context.Background()

	login(t, c, base)
	id := createProduct(t, c, base, uniqueSKU("sheet"), 1)
	key := fmt.Sprintf("products/%d/datasheet", id)
	content := []byte("spec sheet for product; generated by the E2E suite")

	// Upload through the app.
	req, _ := http.NewRequest(http.MethodPut,
		fmt.Sprintf("%s/api/products/%d/datasheet", base, id), bytes.NewReader(content))
	req.Header.Set("Content-Type", "text/plain")
	resp, err := c.Do(req)
	if err != nil {
		t.Fatalf("upload: %v", err)
	}
	io.Copy(io.Discard, resp.Body)
	resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		t.Fatalf("upload: status %d", resp.StatusCode)
	}

	// Read back through the app.
	resp, err = c.Get(fmt.Sprintf("%s/api/products/%d/datasheet", base, id))
	if err != nil {
		t.Fatalf("download: %v", err)
	}
	got, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK || !bytes.Equal(got, content) {
		t.Fatalf("download: status %d body %q", resp.StatusCode, string(got))
	}
	// The download must defend against stored XSS: no MIME sniffing, and the
	// body offered as a download instead of rendered inline.
	if v := resp.Header.Get("X-Content-Type-Options"); v != "nosniff" {
		t.Fatalf("download: X-Content-Type-Options %q (want nosniff)", v)
	}
	if v := resp.Header.Get("Content-Disposition"); !strings.HasPrefix(v, "attachment") {
		t.Fatalf("download: Content-Disposition %q (want attachment)", v)
	}

	// The object is really in MinIO.
	info, err := mc.StatObject(ctx, bucket, key, minio.StatObjectOptions{})
	if err != nil {
		t.Fatalf("minio stat %s/%s: %v", bucket, key, err)
	}
	if info.Size != int64(len(content)) {
		t.Fatalf("minio object size %d (want %d)", info.Size, len(content))
	}

	// Delete through the app; MinIO no longer has it.
	if status := doJSON(t, c, http.MethodDelete,
		fmt.Sprintf("%s/api/products/%d/datasheet", base, id), nil, nil); status != http.StatusNoContent {
		t.Fatalf("delete datasheet: status %d", status)
	}
	if _, err := mc.StatObject(ctx, bucket, key, minio.StatObjectOptions{}); err == nil {
		t.Fatalf("object %s still present in MinIO after delete", key)
	}
	if status := doJSON(t, c, http.MethodGet,
		fmt.Sprintf("%s/api/products/%d/datasheet", base, id), nil, nil); status != http.StatusNotFound {
		t.Fatalf("download after delete: status %d (want 404)", status)
	}
}
